// tests/identity.rs
// Identity extraction from a presented client cert: subject DN + SPKI SHA-256
// fingerprint + issuing CA. No cert => no identity => no conversation.

use zt_policy_gateway::identity::{extract_identity, Identity};

// A test cert generated by the network scripts, injected via env at test time.
// Never a committed real key; this is a public cert path placeholder.
fn load_test_cert_der() -> Vec<u8> {
    let path = std::env::var("ZT_TEST_CLIENT_CERT")
        .unwrap_or_else(|_| "tests/fixtures/alice.der".into());
    std::fs::read(path).expect("test client cert fixture present")
}

#[test]
fn extracts_subject_and_spki_fingerprint() {
    let der = load_test_cert_der();
    let id: Identity = extract_identity(&der).expect("valid cert yields identity");

    // Subject DN is the policy key half; must be non-empty and stable.
    assert!(!id.subject.is_empty(), "subject must be populated");
    assert!(id.subject.contains("CN="), "subject is a DN");

    // SPKI fingerprint is a hex SHA-256 (64 hex chars), bound to the key not
    // the cert serial, so re-issued certs for the same key match.
    assert_eq!(id.spki_sha256.len(), 64, "hex sha-256 of SPKI");
    assert!(id.spki_sha256.chars().all(|c| c.is_ascii_hexdigit()));

    // Issuing CA recorded so the gateway can pin to the org trust root.
    assert!(!id.issuer.is_empty(), "issuer CA recorded");
}

#[test]
fn no_cert_is_no_identity() {
    // Empty/garbage input must not parse into an identity. Fail closed.
    let err = extract_identity(&[]).unwrap_err();
    let _ = err; // any error is acceptable; the point is it does not succeed
    assert!(extract_identity(b"not-a-cert").is_err());
}

#[test]
fn fingerprint_is_deterministic() {
    let der = load_test_cert_der();
    let a = extract_identity(&der).unwrap();
    let b = extract_identity(&der).unwrap();
    assert_eq!(a.spki_sha256, b.spki_sha256, "same cert => same fingerprint");
    assert_eq!(a.subject, b.subject);
}
